#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/titlescreen.h"
#include "images/GreenHill.h"
#include "images/Lose.h"
#include "images/buzz.h"


/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  TITLE_SCREEN,
  PLAY, 
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  struct pacman pm;
  pm.row = 45;
  pm.col = 10;
  pm.color = YELLOW;

  int buttonPresses = -1;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        drawFullScreenImageDMA(titlescreen);
        state = TITLE_SCREEN;
        break;

      case TITLE_SCREEN:
        buttonPresses = -1;
        drawCenteredString(130, 110, 10, 10, "Press Start", WHITE);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          drawFullScreenImageDMA(GreenHill);
          state = PLAY;
        }
        previousButtons = KEY_DOWN(BUTTON_START, BUTTONS);
        break;

      case PLAY:
        drawRectDMA(145, 3, 150, 10, BLACK);
        drawCenteredString(145, 50, 10, 10, "Number of Moves: ", WHITE); 
        drawPresses(buttonPresses, 146, 110, WHITE);
        drawPacman(pm.row, pm.col, pm.color);

        drawRectDMA(35, 0, 70, 5, BLUE);
        drawRectDMA(70, 0, 35, 5, BLUE);
        drawRectDMA(35, 70, 5, 65, BLUE);
        drawRectDMA(70, 35, 5, 60, BLUE);
        drawRectDMA(130, 35, 140, 5, BLUE);
        drawRectDMA(95, 75, 70, 5, BLUE);
        drawRectDMA(50, 145, 5, 50, BLUE);
        drawRectDMA(50, 145, 95, 5, BLUE);
        drawRectDMA(85, 175, 5, 50, BLUE);
        drawRectDMA(85, 175, 65, 5, BLUE);
        if (checkCollision(pm.row, pm.col, 35, 0, 70, 5) | checkCollision(pm.row, pm.col, 70, 0, 35, 5) | checkCollision(pm.row, pm.col, 35, 70, 5, 65)
          | checkCollision(pm.row, pm.col, 70, 35, 5, 60) | checkCollision(pm.row, pm.col, 130, 35, 140, 5) | checkCollision(pm.row, pm.col, 95, 75, 70, 5)
          | checkCollision(pm.row, pm.col, 50, 145, 5, 50) | checkCollision(pm.row, pm.col, 50, 145, 95, 5) | checkCollision(pm.row, pm.col, 85, 175, 5, 50) 
          | checkCollision(pm.row, pm.col, 85, 175, 65, 5)) {
          state = LOSE;
        }
        
        drawRectDMA(55, 235, 5, 30, WHITE);
        if (checkCollision(pm.row, pm.col, 55, 235, 5, 30)) {
          pm.row = 130;
          pm.col = 10;
          fillScreenDMA(WHITE);
          state = WIN;
          break;
        }

        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
            drawPresses(buttonPresses, 146, 110, WHITE);
            buttonPresses++;
          }
          if (pm.col+12 < WIDTH) {
            moveRight(pm.row, pm.col, pm.color, GreenHill);
            pm.col++;
          }
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
            drawPresses(buttonPresses, 146, 110, WHITE);
            buttonPresses++;
          }
          if (pm.col > 0) {
            moveLeft(pm.row, pm.col, pm.color, GreenHill);
            pm.col--;
          }
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
            drawPresses(buttonPresses, 146, 110, WHITE);
            buttonPresses++;
          }
          if (pm.row > 0) {
            moveUp(pm.row, pm.col, pm.color, GreenHill);
            pm.row--;
          }
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
            drawPresses(buttonPresses, 146, 110, WHITE);
            buttonPresses++;
          }
          if (pm.row + 13 < HEIGHT) {
            moveDown(pm.row, pm.col, pm.color, GreenHill);
            pm.row++;
          }
        }

        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          drawFullScreenImageDMA(titlescreen);
          pm.row = 45;
          pm.col = 10;
          state = TITLE_SCREEN;
        }

        previousButtons = KEY_DOWN(BUTTON_START, BUTTONS);
        break;

      case WIN:
        drawPacman(pm.row, pm.col, pm.color);
        drawImageDMA(50, 50, 100, 100, buzz);
        drawCenteredString(15, 100, 10, 10, "Good Job Pac-Man!", BLACK);
        drawCenteredString(30, 80, 10, 10, "You finished the maze in ", BLACK);
        drawPresses(buttonPresses, 31, 160, BLACK);
        drawCenteredString(30, 195, 10, 10, "moves.", BLACK);
        
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          drawFullScreenImageDMA(titlescreen);
          buttonPresses = -1;
          pm.row = 45;
          pm.col = 10;
          state = TITLE_SCREEN;
        }
        break;

      case LOSE:
        drawFullScreenImageDMA(Lose);
        drawCenteredString(110, 110, 10, 10, "Press Start to Try Again.", WHITE);
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          drawFullScreenImageDMA(GreenHill);
          buttonPresses = -1;
          pm.row = 45;
          pm.col = 10;
          state = PLAY;
        }
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          drawFullScreenImageDMA(titlescreen);
          pm.row = 45;
          pm.col = 10;
          state = TITLE_SCREEN;
        }
      break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  return 0;
}
